name: External Events
on:
  repository_dispatch

jobs:
  echo-a-string:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Repository Dispatch"

# This has to live in the default branch or it will NOT run.